cek_lokasi/urls.py
import django.contrib.auth
from django.urls import path, include
from . import views

app_name = 'cek_lokasi'

urlpatterns = [
    # path('', views.cek_lokasi, name='cek_lokasi'),
    path('tambah-faskes/', views.tambah_faskes, name='tambah_faskes'),
    path('tambah-warehouse-satgas/', views.tambah_warehouse_satgas, name='tambah_warehouse_satgas'),
    path('tambah-batch-pengiriman/', views.tambah_batch_pengiriman, name='tambah_batch_pengiriman'),
    path('response-lokasi/', views.perantara, name='perantara'),
    path('response-id/', views.perantara_id, name='perantara_id'),
    path('response-kode/', views.perantara_kode, name='perantara_kode'),
    path('daftar-faskes/', views.insert_to_faskes_table, name='insert_to_faskes_table'),
    path('daftar-warehouse-satgas/', views.insert_to_ws_table, name='insert_to_ws_table'),
    path('faskes/delete/<str:kode_faskes>', views.delete_faskes, name='delete_faskes'),
    path('ws/delete/<str:provinsi>/<str:kabupaten>/<str:kecamatan>/<str:kelurahan>/<str:jalan_no>', views.delete_ws, name='delete_ws'),

]

dashboard/urls.py
import django.contrib.auth
from django.urls import path, include
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.landing, name='landing'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard/admin/', views.dashboard_admin_satgas, name='dashboard-admin-satgas'),
    path('dashboard/faskes/', views.dashboard_petugas_faskes, name='dashboard-petugas-faskes'),
    path('dashboard/supplier/', views.dashboard_supplier, name='dashboard-supplier'),
    path('dashboard/distribusi/', views.dashboard_petugas_distribusi, name='dashboard-petugas-distribusi'),
]

sidia/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('dashboard.urls')),
    path('admin/', admin.site.urls),
    path('user/', include('users.urls')),
    path('cek_lokasi/', include('cek_lokasi.urls')),
    path('kendaraan/', include('kendaraan.urls')),
    path('permohonan/', include('permohonan.urls')),
    path('pesanan/', include('pesanan.urls')),
]

cek_lokasi/models.py
from django.db import models

# Create your models here.

cek_lokasi/views.py
from django.shortcuts import redirect, render
from django.db import connection
from .utils import dictfetchall, tambah_faskes, tambah_ws, faskes_delete, ws_delete, get_id_lokasi

from django.http import JsonResponse, request
from django.http import HttpResponse
import json
from users.decorators import is_user_role_correct
# from cek_lokasi.utils import faskes_delete

def tambah_batch_pengiriman(request):
    cursor = connection.cursor()
    cursor.execute('SET SEARCH_PATH TO SIDIA;')
    cursor.execute(f'''
        SELECT 
            pd.username
        FROM 
            PETUGAS_DISTRIBUSI pd
        WHERE
            pd.username not in (
                SELECT 
                    username_petugas_distribusi
                FROM 
                    BATCH_PENGIRIMAN bp,
                    STATUS_BATCH_PENGIRIMAN sbp
                WHERE
                    sbp.kode = 'PRO' OR sbp.kode = 'OTW'
            )
    ;''')

    petugas_satgas = {
        'petugas_satgas': dictfetchall(cursor)
    }

    return render(request, 'cek_lokasi/add_warehouse_satgas.html', petugas_satgas)


@is_user_role_correct(["ADMIN_SATGAS"])
def tambah_warehouse_satgas(request):
    cursor = connection.cursor()
    cursor.execute('SET SEARCH_PATH TO SIDIA;')
    cursor.execute('SELECT distinct provinsi FROM LOKASI WHERE id not in (SELECT id_lokasi FROM WAREHOUSE_PROVINSI);')

    context = {
        'provinsi_tersedia': dictfetchall(cursor)
    }

    provinsi_tersedia = set()
    for i in context['provinsi_tersedia']:
        for j in i:

            provinsi_tersedia.add(i['provinsi'].lower())

    provinsi_tersedia = sorted(provinsi_tersedia)

    # print(provinsi_tersedia)
    # print(len(provinsi_tersedia))

    provinsi_sisa = {
        'provinsi' : provinsi_tersedia
    }

    return render(request, 'cek_lokasi/add_warehouse_satgas.html', provinsi_sisa)

@is_user_role_correct(["ADMIN_SATGAS"])
def tambah_faskes(request):
    cursor = connection.cursor()
    cursor.execute('SET SEARCH_PATH TO SIDIA;')

    cursor.execute('SELECT Id FROM LOKASI;')
    
    context = {
        'id': dictfetchall(cursor)
    }

    temp_id = set()

    id_lokasi = {}
    for i in context['id']:
        for j in i:
            temp_id.add(i['id'])
        
    temp_id = sorted(temp_id)

    id_lokasi = {
        'id' : temp_id
    }

    cursor.execute('SELECT username FROM PETUGAS_FASKES WHERE username not in (SELECT username_petugas FROM FASKES);')
    context_2 = {
        'username' : dictfetchall(cursor)
    }

    temp_user = set()

    username = {}
    for k in context_2['username']:
        for l in k:
            temp_user.add(k['username'])

    temp_user = sorted(temp_user)

    username = {
        'username':temp_user
    }

    cursor.execute('SELECT Kode FROM TIPE_FASKES;')
    context_3 = {
        'kode' : dictfetchall(cursor)
    }
    temp_kode_tipe_faskes = set()

    kode_tipe_faskes = {}
    for m in context_3['kode']:
        for n in m:
            temp_kode_tipe_faskes.add(m['kode'])

    temp_kode_tipe_faskes = sorted(temp_kode_tipe_faskes)

    kode_tipe_faskes = {
        'kode' : temp_kode_tipe_faskes
    }

    id_lokasi.update(username)
    id_lokasi.update(kode_tipe_faskes)


    return render(request, 'cek_lokasi/add_faskes.html', id_lokasi)


def perantara(request):
    cursor = connection.cursor()
    cursor.execute('SET SEARCH_PATH TO SIDIA;')

    arg = ''
    if request.method == 'GET':
        if 'provinsi' in request.GET:
            arg = request.GET['provinsi'].lower()
  
    cursor.execute(f'''
        SELECT 
            *
        FROM LOKASI
        WHERE 
            provinsi = '{arg}'
        ;''')
    
    print(arg)
 

    data = json.dumps(dictfetchall(cursor))
    print(data)
    
    return JsonResponse(data, safe=False)

def perantara_id(request):
    cursor = connection.cursor()
    cursor.execute('SET SEARCH_PATH TO SIDIA;')
    arg = ''
    if request.method == 'GET':
        if 'id' in request.GET:
            arg = request.GET['id']

    cursor.execute(f'''
        SELECT 
            *
        FROM LOKASI
        WHERE 
            id = '{arg}'
        ;''')
    
    # print(arg)
 

    data = json.dumps(dictfetchall(cursor))
    print(data)
    
    return JsonResponse(data, safe=False)

def perantara_kode(request):
    cursor = connection.cursor()
    cursor.execute('SET SEARCH_PATH TO SIDIA;')
    arg = ''
    if request.method == 'GET':
        if 'kode' in request.GET:
            arg = request.GET['kode']
    
    print(arg)

    cursor.execute(f'''
        SELECT 
            Nama_Tipe
        FROM TIPE_FASKES
        WHERE 
            kode = '{arg}'
        ;''')
    
    # print(arg)
 

    data = json.dumps(dictfetchall(cursor))
    # print(data)
    
    return JsonResponse(data, safe=False)

'''
Trigger no. 5
1. CRUD Fasilitas Kesehatan
    - (CRUD) Admin Satgas
    - (R) Supplier

2. CRUD Warehouse Satgas
    - (CRD) Admin Satgas
    - (R) Supplier    

3. Create Batch Pengiriman (Penentuan
lokasi asal dan tujuan pengiriman)
    - Admin Satgas

'''
@is_user_role_correct(["ADMIN_SATGAS", "SUPPLIER"])
def insert_to_faskes_table(request):
    cursor = connection.cursor()
    cursor.execute('SET SEARCH_PATH TO SIDIA;')
    
    if request.method == 'POST':
        # is form.is_valid():
        form = request.POST
        print(form)

        tambah_faskes(form)
        return redirect ('cek_lokasi:insert_to_faskes_table')

    cursor.execute(f'''
        SELECT
            fk.kode_faskes_nasional as kode_faskes,
            lk.provinsi as provinsi,
            lk.kabkot as kabupaten,
            lk.kecamatan as kecamatan,
            lk.kelurahan as kelurahan,
            lk.jalan_no as jalan_no,
            fk.username_petugas as petugas_faskes,
            tfk.nama_tipe as tipe_faskes
        FROM
            FASKES fk,
            TIPE_FASKES tfk,
            LOKASI lk
        WHERE
            tfk.kode = fk.kode_tipe_faskes AND
            fk.id_lokasi = lk.id
    ;''')

    rows = dictfetchall(cursor)

    if request.session.get('role') == "ADMIN_SATGAS":
        role = "admin_satgas"

    else: 
        role = "others"

    user_role = request.session.get('user_role')
    username = request.session.get('username')

    # print(user_role)

    
        
    return render(request, 'cek_lokasi/daftar_faskes.html', {'rows' : rows, 'user_role' : user_role, 'username' : username })

'''
Trigger no. 5
1. CRUD Fasilitas Kesehatan
    - (CRUD) Admin Satgas
    - (R) Supplier

2. CRUD Warehouse Satgas
    - (CRD) Admin Satgas
    - (R) Supplier    

3. Create Batch Pengiriman (Penentuan
lokasi asal dan tujuan pengiriman)
    - Admin Satgas

'''
@is_user_role_correct(["ADMIN_SATGAS", "SUPPLIER"])
def insert_to_ws_table(request):
    cursor = connection.cursor()
    cursor.execute('SET SEARCH_PATH TO SIDIA;')
    
    if request.session.get('role') == "ADMIN_SATGAS":
        if request.method == 'POST':
            # is form.is_valid():
            form = request.POST
            # print(form)

            tambah_ws(form)
            return redirect ('cek_lokasi:insert_to_ws_table')

    cursor.execute(f'''
        SELECT
            lk.provinsi as provinsi,
            lk.kabkot as kabupaten,
            lk.kecamatan as kecamatan,
            lk.kelurahan as kelurahan,
            lk.jalan_no as jalan_no
        FROM
            WAREHOUSE_PROVINSI wp,
            LOKASI lk
        WHERE
            wp.id_lokasi = lk.id
    ;''')

    rows = dictfetchall(cursor)
    # print(rows)

    user_role = request.session.get('user_role')
    username = request.session.get('username')

    context = {
        'rows' : rows,
        'user_role' : user_role,
        'username' : username,
    }


    count = 1
    for i in range (len(rows)):

        context['no'] = count 
        count = count + 1
    # print(context)

    return render(request, 'cek_lokasi/daftar_warehouse_satgas.html',{'username' : username, 'rows' : rows, 'user_role' : user_role})

@is_user_role_correct(["ADMIN_SATGAS"])
def delete_faskes(request, kode_faskes):
    faskes_delete(kode_faskes)
    return redirect('cek_lokasi:insert_to_faskes_table')

# delete warehoude_satgas
@is_user_role_correct(["ADMIN_SATGAS"])
def delete_ws(request, provinsi,kabupaten, kecamatan, kelurahan, jalan_no):
    id_lokasi = get_id_lokasi(provinsi, kabupaten, kecamatan, kelurahan, jalan_no)
    ws_delete(id_lokasi[0]['id'])
    return redirect('cek_lokasi:insert_to_ws_table')


@is_user_role_correct(["ADMIN_SATGAS"])
def faskes_update(request):
    cursor = connection.cursor()
    cursor.execute('SET SEARCH_PATH TO SIDIA;')

    cursor.execute('SELECT Id FROM LOKASI;')
    
    context = {
        'id': dictfetchall(cursor)
    }

    temp_id = set()

    id_lokasi = {}
    for i in context['id']:
        for j in i:
            temp_id.add(i['id'])
        
    temp_id = sorted(temp_id)

    id_lokasi = {
        'id' : temp_id
    }

    cursor.execute('SELECT username FROM PETUGAS_FASKES WHERE username not in (SELECT username_petugas FROM FASKES);')
    context_2 = {
        'username' : dictfetchall(cursor)
    }

    temp_user = set()

    username = {}
    for k in context_2['username']:
        for l in k:
            temp_user.add(k['username'])

    temp_user = sorted(temp_user)

    username = {
        'username':temp_user
    }

    cursor.execute('SELECT Kode FROM TIPE_FASKES;')
    context_3 = {
        'kode' : dictfetchall(cursor)
    }
    temp_kode_tipe_faskes = set()

    kode_tipe_faskes = {}
    for m in context_3['kode']:
        for n in m:
            temp_kode_tipe_faskes.add(m['kode'])

    temp_kode_tipe_faskes = sorted(temp_kode_tipe_faskes)

    kode_tipe_faskes = {
        'kode' : temp_kode_tipe_faskes
    }

    id_lokasi.update(username)
    id_lokasi.update(kode_tipe_faskes)

    return render(request, 'cek_lokasi/add_faskes.html', id_lokasi)





    

cek_lokasi/templates/cek_lokasi/add_warehouse_satgas.html
<!DOCTYPE html>

{% extends 'base.html' %}
{% load static %}

{% block meta %}
  <link rel="stylesheet" href="{% static 'cek_lokasi/cek_lokasi.css' %}">
{% endblock %}

{% block content %}

  <div class="w-screen h-screen flex">


    <section class="w-1/2 p-16 h-full bg-gradient-to-r from-purple-400 via-pink-500 to-red-500 flex flex-col justify-center items-center">
      <img src="{% static 'warehousesatgas/assets/warehouse.png' %}" alt="login-asset" />
      <a class="outline-none focus:outline-none active:outline-none" href="{% url 'dashboard:landing' %}">
        <h5 class="text-white text-xl mt-12">
          Kembali ke <span class="font-bold text-yellow-400">Halaman Depan</span>

        </h5>
      </a>
    </section>

    <section class="w-1/2 h-full bg-gray-100 flex flex-col text-center justify-center items-center">
      <div class="w-7/15 p-10 bg-white rounded-2xl filter drop-shadow-xl">
        <h5 class="text-pink-500 font-bold text-5xl">Tambah Warehouse Satgas Baru</h5>
        <h6 class="mt-2">Silahkan Masukan Data Warehouse Satgas Baru.</h6>
        


        <form class="flex flex-col w-full justify-center items-center mt-5" method="POST" action="{% url 'cek_lokasi:insert_to_ws_table' %}">
          {% csrf_token %}
          <div style="margin: -5px 0;" class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label getmdl-select getmdl-select__fix-height w-10/12">
            <input required type="text" value="" class="mdl-textfield__input" id="provinsi">
            <input type="hidden" value="" name="pilih-provinsi">
            <i class="mdl-icon-toggle__label material-icons">keyboard_arrow_down</i>
            <label for="sample5" class="mdl-textfield__label">Provinsi</label>
            <ul for="sample5" class="mdl-menu mdl-menu--bottom-left mdl-js-menu">

                {% for i in provinsi %}
                  <li class="mdl-menu__item" data-val="provinsi">{{ i | title }}</li>
                {% endfor %}

            </ul>
          </div>
          <div id="id-lokasi-select" style="margin: -5px 0;" class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label getmdl-select getmdl-select__fix-height w-10/12">
            <input required type="text" value="" class="mdl-textfield__input" id="id_lokasi">
            <input type="hidden" value="" name="pilih_id">
            <i class="mdl-icon-toggle__label material-icons">keyboard_arrow_down</i>
            <label for="sample6" class="mdl-textfield__label">Id Lokasi</label>
            <ul for="sample6" class="mdl-menu mdl-menu--bottom-left mdl-js-menu" id="id">

              
            </ul>
          </div>


          <div style="margin: -5px 0;" class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label w-10/12">
            <input required disable class="mdl-textfield__input" name="nama-organisasi" type="text" autocorrect="off" spellcheck="false" autocomplete="off" readonly onfocus="this.removeAttribute('readonly');">
            <label class="mdl-textfield__label text-black" for="sample1" id ="generate_kabupaten"></label>
            <!-- tambahin yang nyimpen hasil select dari kursor -->


          </div>

          <div style="margin: -5px 0;" class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label w-10/12">
            <input required disable class="mdl-textfield__input" name="nama-organisasi" type="text" autocorrect="off" spellcheck="false" autocomplete="off" readonly onfocus="this.removeAttribute('readonly');">
            <label class="mdl-textfield__label text-black" for="sample1" id ="generate_kecamatan"></label>
            <!-- tambahin yang nyimpen hasil select dari kursor -->


          </div>

          <div style="margin: -5px 0;" class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label w-10/12">
            <input required disable class="mdl-textfield__input" name="nama-organisasi" type="text" autocorrect="off" spellcheck="false" autocomplete="off" readonly onfocus="this.removeAttribute('readonly');">
            <label class="mdl-textfield__label text-black" for="sample1" id ="generate_kelurahan"></label>
            <!-- tambahin yang nyimpen hasil select dari kursor -->


          </div>

          <div style="margin: -5px 0;" class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label w-10/12">
            <input required disable class="mdl-textfield__input" name="nama-organisasi" type="text" autocorrect="off" spellcheck="false" autocomplete="off" readonly onfocus="this.removeAttribute('readonly');">
            <label class="mdl-textfield__label text-black" for="sample1" id ="generate_no"></label>
            <!-- tambahin yang nyimpen hasil select dari kursor -->


          </div>
          <div class="flex mt-5">
            <a href="{% url 'cek_lokasi:insert_to_ws_table' %}" class="focus:outline-none">
              <button type="submit" class="bg-gradient-to-r from-blue-500 to-yellow-400 font-bold text-white py-2 px-4 rounded mr-2">
                Tambah
              </button>
              </a>
          </div>
        </form>
      </div>
    </section>
  </div>
{% endblock %}

{% block script %}
  <script>
    $('#provinsi').on('change', function(){
      var temp_provinsi = $(this).val()
      console.log(temp_provinsi);


      var url_untuk_dipanggil = "/cek_lokasi/response-lokasi"

      $.ajax({
        method : 'GET',

        data:
        {'provinsi' : temp_provinsi},
        url : url_untuk_dipanggil,
        success : function(out){

          var obj_hasil = $('#id');
          var generate_kabupaten = $('#generate_kabupaten');
          var generate_kecamatan = $('#generate_kecamatan');
          var generate_kelurahan = $('#generate_kelurahan');
          var generate_no = $('#generate_no');
          obj_hasil.empty();
          generate_kabupaten.empty();
          generate_kecamatan.empty();
          generate_kelurahan.empty();
          generate_no.empty();
          const obj = JSON.parse(out);

          for(i = 0; i < obj.length; i++){
            var dict = obj[i]
            console.log(dict['id'])

            obj_hasil.append('<li class="mdl-menu__item" data-val="' + dict['id'] + '">'+ dict['id'] + '</li>');
            generate_kabupaten.append('<h6 class="mt-2">Kabupaten / Kota : '+dict['kabkot'] +'</h6>')
            generate_kecamatan.append('<h6 class="mt-2">Kecamatan        : '+dict['kecamatan'] +'</h6>')
            generate_kelurahan.append('<h6 class="mt-2">Kelurahan        : '+dict['kelurahan'] +'</h6>')
            generate_no.append('<h6 class="mt-2">No Jalan                : '+dict['jalan_no'] +'</h6>')
          }

          getmdlSelect.init('#id-lokasi-select');

        }
      })

    });
  </script>

{% endblock %}

cek_lokasi/templates/cek_lokasi/daftar_faskes.html
<!DOCTYPE html>

{% extends 'base.html' %}
{% load static %}

{% block meta %}
  <link rel="stylesheet" href="{% static 'cek_lokasi/cek_lokasi.css' %}">
{% endblock %}

{% block content %}
  <div class="bg-gray-100">
    <section style="height: 40vh;" class="w-full bg-gradient-to-b from-blue-500  to-yellow-200 flex flex-col justify-center items-center">
      <h2 class="text-white font-bold text-6xl">Fasilitas Kesehatan</span></h2>
      <div class="flex mt-10">
        <div class="bg-gray-200 text-pink-500 font-bold cursor-default text-xl py-1 px-2 mx-1 rounded">👤 {{ username }}</div>
        <div class="bg-gray-200 text-pink-500 font-bold cursor-default text-xl py-1 px-2 mx-1 rounded">👨‍💼 {{ user_role }}</div>
      </div>
      <a href="{% url 'dashboard:dashboard' %}" class="focus:outline-none">
        <button type="button" class="bg-blue-400 mx-2 w-56 text-white font-bold py-2 px-4 border rounded mr-2 mt-10 focus:outline-none focus:ring">
          Kembali ke Dashboard
        </button>
      </a>
    </section>
    <section style="min-height: 60vh;" class="px-20 py-10">
      <table class="mdl-data-table mdl-js-data-table mdl-shadow--2dp w-full">
        <thead>
          <tr>
            <th class="mdl-data-table__cell--non-numeric">Kode Faskes</th>
            <th class="mdl-data-table__cell--non-numeric">Lokasi</th>
            <th class="mdl-data-table__cell--non-numeric">Petugas Faskes</th>
            <th class="mdl-data-table__cell--non-numeric">Tipe Faskes</th>
            {% if user_role == "ADMIN_SATGAS" %}
                <th class="mdl-data-table__cell--non-numeric">Action</th>
            {% endif %}
 
          </tr>
        </thead>
        <tbody>
          {% for isi in rows %}
            <tr>
              <td class="mdl-data-table__cell--non-numeric">{{ isi.kode_faskes }}</td>
              <td class="mdl-data-table__cell--non-numeric">
                  <p>Provnsi            : {{ isi.provinsi }}</p>
                  <p>Kabupaten / Kota   : {{ isi.kabupaten }}</p>
                  <p>Kecamatan          : {{ isi.kecamatan }}</p>
                  <p>Kelurahan          : {{ isi.kelurahan }}</p>
                  <p>Jalan No           : {{ isi.jalan_no }}</p>

            </td>
            
              <td class="mdl-data-table__cell--non-numeric">{{ isi.petugas_faskes }}</td>
              <td class="mdl-data-table__cell--non-numeric">{{ isi.tipe_faskes }}</td>

              {% if user_role == "ADMIN_SATGAS" %}
                <td class="mdl-data-table__cell--non-numeric">
                    <div class="flex">
                        <a href="{% url 'cek_lokasi:delete_faskes' isi.kode_faskes %}">
                            <div style="margin: 0 4.5px;" class="font-bold cursor-pointer hover:bg-red-800 bg-red-700 p-2 min-w-7 h-7 flex items-center justify-center text-white rounded">Delete</div>
                        </a>
                        <div style="margin: 0 4.5px;" class="font-bold cursor-pointer hover:bg-green-500 bg-green-600 p-2 min-w-7 h-7 flex items-center justify-center text-white rounded">Update</div>
                    </div>
                </td>
              {% endif %}
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </section>
  </div>
{% endblock %}

  

cek_lokasi/templates/cek_lokasi/daftar_warehouse_satgas.html
<!DOCTYPE html>

{% extends 'base.html' %}
{% load static %}

{% block meta %}
  <link rel="stylesheet" href="{% static 'cek_lokasi/cek_lokasi.css' %}">
{% endblock %}

{% block content %}
  <div class="bg-gray-100">
    <section style="height: 40vh;" class="w-full bg-gradient-to-b from-red-400  via-pink-500 to-purple-500 flex flex-col justify-center items-center">
      <h2 class="text-white font-bold text-6xl">Warehouse Satgas</span></h2>
      <div class="flex mt-10">
        <div class="bg-gray-200 text-pink-500 font-bold cursor-default text-xl py-1 px-2 mx-1 rounded">👤 {{ username }}</div>
        <div class="bg-gray-200 text-pink-500 font-bold cursor-default text-xl py-1 px-2 mx-1 rounded">👨‍💼 {{ user_role }}</div>
      </div>
      <a href="{% url 'dashboard:dashboard' %}" class="focus:outline-none">
        <button type="button" class="bg-blue-400 mx-2 w-56 text-white font-bold py-2 px-4 border rounded mr-2 mt-10 focus:outline-none focus:ring">
          Kembali ke Dashboard
        </button>
      </a>
    </section>
    <section style="min-height: 60vh;" class="px-20 py-10">
      <table class="mdl-data-table mdl-js-data-table mdl-shadow--2dp w-full">
        <thead>
          <tr>
            <th class="mdl-data-table__cell--non-numeric">No.</th>
            <th class="mdl-data-table__cell--non-numeric">Provinsi</th>
            <th class="mdl-data-table__cell--non-numeric">Lokasi</th>
            <!-- <th class="mdl-data-table__cell--non-numeric">Tipe Faskes</th> -->
         
            {% if user_role == "ADMIN_SATGAS" %}
                <th class="mdl-data-table__cell--non-numeric">Action</th>
            {% endif %}
          </tr>
        </thead>
        <tbody>
            {% for isi in rows %}
              <tr>
                <td class="mdl-data-table__cell--non-numeric" id="increment">{{ loop.index }}</td>
                <td class="mdl-data-table__cell--non-numeric">{{ isi.provinsi }}</td>
                <td class="mdl-data-table__cell--non-numeric">
                    <p>Kabupaten / Kota   : {{ isi.kabupaten }}</p>
                    <p>Kecamatan          : {{ isi.kecamatan }}</p>
                    <p>Kelurahan          : {{ isi.kelurahan }}</p>
                    <p>Jalan No           : {{ isi.jalan_no }}</p>
  
              </td>
  
                {% if user_role == "ADMIN_SATGAS" %}
                  <td class="mdl-data-table__cell--non-numeric">
                      <div class="flex">
                        <a href="{% url 'cek_lokasi:delete_ws' isi.provinsi isi.kabupaten isi.kecamatan isi.kelurahan isi.jalan_no %}">
                            <div style="margin: 0 4.5px;" class="font-bold cursor-pointer hover:bg-red-800 bg-red-700 p-2 min-w-7 h-7 flex items-center justify-center text-white rounded">Delete</div>
                        </a>
                      <div style="margin: 0 4.5px;" class="font-bold cursor-pointer hover:bg-green-500 bg-green-600 p-2 min-w-7 h-7 flex items-center justify-center text-white rounded">Update</div>
                      </div>
                  </td>

                {% endif %}
              </tr>
            {% endfor %}
          </tbody>
      </table>
    </section>
  </div>
{% endblock %}

{% block script %}
<script>
    var addSerialNumber = function () {
        var i = 1
        $('table tr').each(function(index) {
            $(this).find('td:nth-child(1)').html(index-1+i);
        });
    };

    addSerialNumber();

</script>
{% endblock %}
  