dashboard/urls.py
import django.contrib.auth
from django.urls import path, include
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.landing, name='landing'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard/admin/', views.dashboard_admin_satgas, name='dashboard-admin-satgas'),
    path('dashboard/faskes/', views.dashboard_petugas_faskes, name='dashboard-petugas-faskes'),
    path('dashboard/supplier/', views.dashboard_supplier, name='dashboard-supplier'),
    path('dashboard/distribusi/', views.dashboard_petugas_distribusi, name='dashboard-petugas-distribusi'),
]

pesanan/urls.py
import django.contrib.auth
from django.urls import path, include
from . import views

app_name = 'pesanan'

urlpatterns = [
    path('pesanan/', views.pesanan, name='pesanan'),
    path('pesanan/create/', views.pesanan_create, name='pesanan-create'),
    path('riwayat/process/<str:no_transaksi>/', views.riwayat_process, name='riwayat-process'),
    path('riwayat/reject/<str:no_transaksi>/', views.riwayat_reject, name='riwayat-reject'),
    path('riwayat/problem/<str:no_transaksi>/', views.riwayat_problem, name='riwayat-problem'),
    path('riwayat/finish/<str:no_transaksi>/', views.riwayat_finish, name='riwayat-finish'),
    path('riwayat/status/<str:no_transaksi>/', views.riwayat_status, name='riwayat-status'),
    path('stok-faskes/', views.stok_faskes, name='stok-faskes'),
    path('stok-faskes/create/', views.stok_faskes_create, name='stok-faskes-create'),
    path('stok-faskes/update/<str:kode_faskes>/<str:kode_item>', views.stok_faskes_update, name='stok-faskes-update'),
    path('stok-faskes/delete/<str:kode_faskes>/<str:kode_item>', views.stok_faskes_delete, name='stok-faskes-delete'),
]

sidia/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('dashboard.urls')),
    path('admin/', admin.site.urls),
    path('user/', include('users.urls')),
    path('cek_lokasi/', include('cek_lokasi.urls')),
    path('kendaraan/', include('kendaraan.urls')),
    path('permohonan/', include('permohonan.urls')),
    path('pesanan/', include('pesanan.urls')),
]

users/urls.py
import django.contrib.auth
from django.urls import path, include
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),
]

pesanan/models.py
from django.db import models

# Create your models here.

pesanan/views.py
from django.db import connection
from django.shortcuts import render, redirect

from .utils import (dictfetchall, pesanan_query_admin,
                pesanan_query_supplier, stok_faskes_query,
                stok_faskes_create_query, stok_faskes_create_insert,
                stok_faskes_update_query, stok_faskes_update_update,
                stok_faskes_delete_delete, riwayat_create_ops,
                riwayat_status_query, pesanan_delete_delete)
from users.decorators import is_user_role_correct

'''
Trigger no. 3
6. CRUD Pesanan Sumber Daya
    - Admin (CRUD)
    - Supplier (R)
7. CR Riwayat Status Pesanan Sumber Daya
    - Admin (R)
    - Supplier (CR)
8. CRUD Stok Fasilitas Kesehatan
    - Admin (CRUD)
    - Petugas Faskes (R)
'''

@is_user_role_correct(["ADMIN_SATGAS", "SUPPLIER"])
def pesanan(request):
    user_role = request.session.get('user_role')
    username = request.session.get('username')

    order_data = []
    if (user_role == "ADMIN_SATGAS"):
        order_data = pesanan_query_admin(user_role, username)
    elif (user_role == "SUPPLIER"):
        order_data = pesanan_query_supplier(user_role, username)

    user_role = user_role.split("_")
    user_role = " ".join(user_role).lower().title()

    context = {}
    context['order_data'] = order_data if order_data != [] else []
    context['user_role'] = user_role
    context['username'] = username

    return render(request, 'pesanan/pesanan.html', context)

@is_user_role_correct(["ADMIN_SATGAS"])
def pesanan_create(request):
    user_role = request.session.get('user_role')
    username = request.session.get('username')

    return render(request, 'pesanan/pesanan-create.html')

@is_user_role_correct(["ADMIN_SATGAS"])
def pesanan_delete(request, no_transaksi):
    pesanan_delete(no_transaksi)
    redirect('pesanan:pesanan')

@is_user_role_correct(["ADMIN_SATGAS", "PETUGAS_FASKES"])
def stok_faskes(request):
    user_role = request.session.get('user_role')
    username = request.session.get('username')

    stock_data = stok_faskes_query(user_role, username)

    user_role = user_role.split("_")
    user_role = " ".join(user_role).lower().title()

    context = {}
    context['stock_data'] = stock_data if stock_data != [] else []
    context['user_role'] = user_role
    context['username'] = username

    return render(request, 'pesanan/stok-faskes.html', context)

@is_user_role_correct(["ADMIN_SATGAS"])
def stok_faskes_create(request):
    [faskes_data, item_data] = stok_faskes_create_query()

    if request.method == 'POST':
        form = request.POST
        stok_faskes_create_insert(form)
        return redirect('pesanan:stok-faskes')

    context = {}
    context['faskes_data'] = faskes_data
    context['item_data'] = item_data

    return render(request, 'pesanan/stok-faskes-create.html', context)

@is_user_role_correct(["ADMIN_SATGAS"])
def stok_faskes_update(request, kode_faskes, kode_item):
    [faskes_data, item_data] = stok_faskes_update_query(kode_faskes, kode_item)

    if request.method == 'POST':
        form = request.POST
        stok_faskes_update_update(form)
        return redirect('pesanan:stok-faskes')

    context = {}
    context['faskes_data'] = faskes_data[0]
    context['item_data'] = item_data[0]

    return render(request, 'pesanan/stok-faskes-update.html', context)

@is_user_role_correct(["ADMIN_SATGAS"])
def stok_faskes_delete(request, kode_faskes, kode_item):
    stok_faskes_delete_delete(kode_faskes, kode_item)
    return redirect('pesanan:stok-faskes')

@is_user_role_correct(["SUPPLIER"])
def riwayat_process(request, no_transaksi):
    username = request.session.get('username')
    riwayat_create_ops(username, no_transaksi, "PRO-SUP")
    return redirect('pesanan:pesanan')

@is_user_role_correct(["SUPPLIER"])
def riwayat_reject(request, no_transaksi):
    username = request.session.get('username')
    riwayat_create_ops(username, no_transaksi, "REJ-SUP")
    return redirect('pesanan:pesanan')

@is_user_role_correct(["SUPPLIER"])
def riwayat_problem(request, no_transaksi):
    username = request.session.get('username')
    riwayat_create_ops(username, no_transaksi, "MAS-SUP")
    return redirect('pesanan:pesanan')

@is_user_role_correct(["SUPPLIER"])
def riwayat_finish(request, no_transaksi):
    username = request.session.get('username')
    riwayat_create_ops(username, no_transaksi, "FIN-SUP")
    return redirect('pesanan:pesanan')

@is_user_role_correct(["ADMIN_SATGAS", "SUPPLIER"])
def riwayat_status(request, no_transaksi):
    user_role = request.session.get('user_role')
    username = request.session.get('username')

    riwayat_data = riwayat_status_query(no_transaksi)

    count = 1
    for riwayat in riwayat_data:
        riwayat['no'] = count
        count += 1

    user_role = user_role.split("_")
    user_role = " ".join(user_role).lower().title()

    context = {}
    context['riwayat_data'] = riwayat_data
    context['no_transaksi'] = no_transaksi
    context['user_role'] = user_role
    context['username'] = username

    return render(request, 'pesanan/riwayat.html', context)

pesanan/templates/pesanan/pesanan-create.html
<!DOCTYPE html>

{% extends 'base.html' %}
{% load static %}

{% block content %}
  <div class="w-screen h-screen flex">
    <section class="w-1/2 p-16 h-full bg-gradient-to-b from-red-300 via-pink-400 to-pink-500 flex flex-col justify-center items-center">
      <img src="{% static 'dashboard/assets/login-asset.png' %}" alt="login-asset" />
      <a class="outline-none focus:outline-none active:outline-none" href="{% url 'pesanan:pesanan' %}">
        <h5 class="text-white text-xl mt-12">
          Kembali ke <span class="font-bold text-yellow-400">Pesanan Sumber Daya</span>
        </h5>
      </a>
    </section>

    <section class="w-1/2 h-full bg-gray-100 flex flex-col text-center justify-center items-center">
      <div class="w-10/12 p-10 bg-white rounded-2xl filter drop-shadow-xl">
        <h5 class="text-pink-500 font-bold text-5xl">Buat Pesanan</h5>
        <h6 class="mt-2">Membuat pesanan sumber daya.</h6>

        <form class="flex flex-col w-full justify-center items-center mt-10" method="POST" action="{% url 'users:login' %}">
          {% csrf_token %}
          <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label w-11/12">
            <input maxlength="50" required class="mdl-textfield__input" name="username" type="text" autocorrect="off" spellcheck="false" autocomplete="off" readonly onfocus="this.removeAttribute('readonly');">
            <label class="mdl-textfield__label" for="sample1">Username</label>
          </div>
          <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label w-11/12 mt-2">
            <input maxlength="20" required class="mdl-textfield__input" name="password" type="password" autocorrect="off" spellcheck="false" autocomplete="off" readonly onfocus="this.removeAttribute('readonly');">
            <label class="mdl-textfield__label" for="sample1">Password</label>
          </div>
          {% for message in messages %}
            <div class="text-red-400">{{ message }}</div>
          {% endfor %}
          <div class="flex mt-10">
            <button type="submit" class="bg-transparent mx-2 w-36 bg-green-400 font-bold text-white py-2 px-4 border border-green-400 rounded mr-2">
              Masuk
            </button>
            <a href="{% url 'users:register' %}" class="focus:outline-none">
              <button type="button" class="bg-transparent mx-2 w-36 text-gray-400 font-bold py-2 px-4 border border-gray-400 rounded mr-2 focus:outline-none focus:ring focus:border-gray-500">
                Daftar
              </button>
            </a>
          </div>
        </form>
      </div>
    </section>
  </div>
{% endblock %}

pesanan/templates/pesanan/pesanan.html
<!DOCTYPE html>

{% extends 'base.html' %}
{% load static %}

{% block meta %}
{% endblock %}

{% block content %}
  <div class="bg-gray-100">
    <section style="height: 40vh;" class="w-full bg-gradient-to-b from-red-300 to-pink-400 flex flex-col justify-center items-center">
      <h2 class="text-white font-bold text-6xl">Pesanan Sumber Daya</span></h2>
      <div class="flex mt-10">
        <div class="bg-gray-200 text-pink-500 font-bold cursor-default text-xl py-1 px-2 mx-1 rounded">👤 {{ username }}</div>
        <div class="bg-gray-200 text-pink-500 font-bold cursor-default text-xl py-1 px-2 mx-1 rounded">👨‍💼 {{ user_role }}</div>
      </div>
      <a href="{% url 'dashboard:dashboard' %}" class="focus:outline-none">
        <button type="button" class="bg-blue-400 mx-2 w-56 text-white font-bold py-2 px-4 border rounded mr-2 mt-10 focus:outline-none focus:ring">
          Kembali ke Dashboard
        </button>
      </a>
    </section>
    <section style="min-height: 60vh;" class="px-20 py-10">
      <table class="mdl-data-table mdl-js-data-table mdl-shadow--2dp w-full">
        <thead>
          <tr>
            <th class="mdl-data-table__cell--non-numeric">No. Transaksi</th>
            <th class="mdl-data-table__cell--non-numeric">Petugas Satgas</th>
            <th class="mdl-data-table__cell--non-numeric">Tanggal</th>
            <th>Total Berat</th>
            <th>Total Item</th>
            <th>Total Harga</th>
            <th class="mdl-data-table__cell--non-numeric">Status</th>
            <th class="mdl-data-table__cell--non-numeric">Action</th>
          </tr>
        </thead>
        <tbody>
          {% for order in order_data %}
            <tr>
              <td class="mdl-data-table__cell--non-numeric">TOR{{ order.nomor }}</td>
              <td class="mdl-data-table__cell--non-numeric">{{ order.username_admin_satgas }}</td>
              <td class="mdl-data-table__cell--non-numeric">{{ order.tanggal }}</td>
              <td>{{ order.total_berat }} Kg</td>
              <td>{{ order.total_item }}</td>
              <td>Rp {{ order.total_harga }}</td>
              <td class="mdl-data-table__cell--non-numeric">{{ order.kode }}</td>
              <td class="mdl-data-table__cell--non-numeric">
                <div class="flex">
                  {% if order.kode == "REQ-SUP" %}
                    {% if user_role == "Admin Satgas" %}
                      <a href="">
                        <div style="margin: 0 4.5px;" class="font-bold cursor-pointer hover:bg-red-800 bg-red-700 p-2 min-w-7 h-7 flex items-center justify-center text-white rounded">Delete</div>
                      </a>
                      <a href="">
                        <div style="margin: 0 4.5px;" class="font-bold cursor-pointer hover:bg-green-500 bg-green-600 p-2 min-w-7 h-7 flex items-center justify-center text-white rounded">Update</div>
                      </a>
                    {% elif user_role == "Supplier" %}
                      <a href="{% url 'pesanan:riwayat-reject' order.nomor %}">
                        <div style="margin: 0 4.5px;" class="font-bold cursor-pointer hover:bg-red-500 bg-red-600 p-2 min-w-7 h-7 flex items-center justify-center text-white rounded">Reject</div>
                      </a>
                      <a href="{% url 'pesanan:riwayat-process' order.nomor %}">
                        <div style="margin: 0 4.5px;" class="font-bold cursor-pointer hover:bg-blue-500 bg-blue-400 p-2 min-w-7 h-7 flex items-center justify-center text-white rounded">Process</div>
                      </a>
                    {% endif %}
                  {% endif %}
                </div>
                {% if user_role == "Supplier" %}
                  <div class="flex mt-2">
                    <a href="">
                      <div style="margin: 0 4.5px;" class="font-bold cursor-pointer hover:bg-blue-700 bg-blue-600 p-2 min-w-7 h-7 flex items-center justify-center text-white rounded">Detail</div>
                    </a>
                    <a href="{% url 'pesanan:riwayat-status' order.nomor %}">
                      <div style="margin: 0 4.5px;" class="font-bold cursor-pointer hover:bg-yellow-500 bg-yellow-400 p-2 min-w-7 h-7 flex items-center justify-center text-white rounded">Riwayat Status</div>
                    </a>
                    {% if order.kode == "PRO-SUP" %}
                      <a href="{% url 'pesanan:riwayat-problem' order.nomor %}">
                        <div style="margin: 0 4.5px;" class="font-bold cursor-pointer hover:bg-green-700 bg-green-600 p-2 min-w-7 h-7 flex items-center justify-center text-white rounded">Selesai</div>
                      </a>
                    {% endif %}
                  </div>
                  <div class="flex mt-2">
                    {% if order.kode == "PRO-SUP" %}
                      <a href="{% url 'pesanan:riwayat-finish' order.nomor %}">
                        <div style="margin: 0 4.5px;" class="font-bold cursor-pointer hover:bg-red-500 bg-red-400 p-2 min-w-7 h-7 flex items-center justify-center text-white rounded">Selesai Dengan Masalah</div>
                      </a>
                    {% endif %}
                  </div>
                {% endif %}
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </section>
  </div>
{% endblock %}

pesanan/templates/pesanan/riwayat.html
<!DOCTYPE html>

{% extends 'base.html' %}
{% load static %}

{% block meta %}
{% endblock %}

{% block content %}
  <div class="bg-gray-100">
    <section style="height: 40vh;" class="w-full bg-gradient-to-b from-red-300 to-pink-400 flex flex-col justify-center items-center">
      <h2 class="text-white font-bold text-6xl">Riwayat Status Pesanan TOR{{ no_transaksi }}</span></h2>
      <div class="flex mt-10">
        <div class="bg-gray-200 text-pink-500 font-bold cursor-default text-xl py-1 px-2 mx-1 rounded">👤 {{ username }}</div>
        <div class="bg-gray-200 text-pink-500 font-bold cursor-default text-xl py-1 px-2 mx-1 rounded">👨‍💼 {{ user_role }}</div>
      </div>
      <a href="{% url 'pesanan:pesanan' %}" class="focus:outline-none">
        <button type="button" class="bg-blue-400 mx-2 w-56 text-white font-bold py-2 px-4 border rounded mr-2 mt-10 focus:outline-none focus:ring">
          Kembali ke Riwayat Status Pesanan
        </button>
      </a>
    </section>
    <section style="min-height: 60vh;" class="px-20 py-10">
      <table class="mdl-data-table mdl-js-data-table mdl-shadow--2dp w-full">
        <thead>
          <tr>
            <th class="mdl-data-table__cell--non-numeric">No.</th>
            <th class="mdl-data-table__cell--non-numeric">Kode Status</th>
            <th class="mdl-data-table__cell--non-numeric">Status</th>
            <th class="mdl-data-table__cell--non-numeric">Username Supplier</th>
            <th class="mdl-data-table__cell--non-numeric">Tanggal Persetujuan</th>
          </tr>
        </thead>
        <tbody>
          {% for riwayat in riwayat_data %}
            <tr>
              <td class="mdl-data-table__cell--non-numeric">{{ riwayat.no }}</td>
              <td class="mdl-data-table__cell--non-numeric">{{ riwayat.kode_status_pesanan }}</td>
              <td class="mdl-data-table__cell--non-numeric">{{ riwayat.nama }}</td>
              <td class="mdl-data-table__cell--non-numeric">{{ riwayat.username_supplier }}</td>
              <td class="mdl-data-table__cell--non-numeric">{{ riwayat.tanggal }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </section>
  </div>
{% endblock %}

pesanan/templates/pesanan/stok-faskes-create.html
<!DOCTYPE html>

{% extends 'base.html' %}
{% load static %}

{% block content %}
  <div class="w-screen h-screen flex">
    <section class="w-1/2 p-16 h-full bg-gradient-to-b from-red-300 via-pink-400 to-pink-500 flex flex-col justify-center items-center">
      <img src="{% static 'dashboard/assets/login-asset.png' %}" alt="login-asset" />
      <a class="outline-none focus:outline-none active:outline-none" href="{% url 'pesanan:stok-faskes' %}">
        <h5 class="text-white text-xl mt-12">
          Kembali ke <span class="font-bold text-yellow-400">Stok Fasilitas Kesehatan</span>
        </h5>
      </a>
    </section>

    <section class="w-1/2 h-full bg-gray-100 flex flex-col text-center justify-center items-center">
      <div class="w-9/12 p-10 bg-white rounded-2xl filter drop-shadow-xl">
        <h5 class="text-pink-500 font-bold text-5xl">Buat Stok Faskes</h5>
        <h6 class="mt-2">Membuat stok fasilitas kesehatan.</h6>

        <form class="flex flex-col w-full justify-center items-center mt-10" method="POST" action="{% url 'pesanan:stok-faskes-create' %}">
          {% csrf_token %}
          <div style="margin: -5px 0;" class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label getmdl-select getmdl-select__fix-height w-10/12">
            <input type="text" value="" class="mdl-textfield__input" id="kode-faskes" readonly onchange="handleKodeFaskesSelect(this.value)">
            <input type="hidden" value="" name="kode-faskes">
            <i class="mdl-icon-toggle__label material-icons">keyboard_arrow_down</i>
            <label for="kode-faskes" class="mdl-textfield__label">Kode Faskes</label>
            <ul for="kode-faskes" class="mdl-menu mdl-menu--bottom-left mdl-js-menu">
              {% for faskes in faskes_data %}
                <li class="mdl-menu__item" id="{{ faskes.kode_faskes_nasional }}" data-val="{{ faskes.kode_faskes_nasional }}" data-nama="{{ faskes.nama_tipe }}">{{ faskes.kode_faskes_nasional }}</li>
              {% endfor %}
            </ul>
          </div>
          <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label w-10/12 pointer-events-none">
            <input required class="mdl-textfield__input pointer-events-none" name="nama-faskes" id="nama-faskes" type="text" autocorrect="off" spellcheck="false" autocomplete="off" readonly onfocus="this.removeAttribute('readonly');">
            <label class="mdl-textfield__label" for="sample1">Nama Faskes</label>
          </div>
          <div style="margin: -5px 0;" class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label getmdl-select getmdl-select__fix-height w-10/12">
            <input type="text" value="" class="mdl-textfield__input" id="kode-item-sumber-daya" readonly onchange="handleItemSumberDayaSelect(this.value)">
            <input type="hidden" value="" name="kode-item-sumber-daya">
            <i class="mdl-icon-toggle__label material-icons">keyboard_arrow_down</i>
            <label for="kode-item-sumber-daya" class="mdl-textfield__label">Kode Item Sumber Daya</label>
            <ul for="kode-item-sumber-daya" class="mdl-menu mdl-menu--bottom-left mdl-js-menu">
              {% for item in item_data %}
                <li class="mdl-menu__item" id="{{ item.kode }}" data-val="{{ item.kode }}" data-nama="{{ item.nama }}">{{ item.kode }}</li>
              {% endfor %}
            </ul>
          </div>
          <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label w-10/12 pointer-events-none">
            <input required class="mdl-textfield__input pointer-events-none" name="item-sumber-daya" id="item-sumber-daya" type="text" autocorrect="off" spellcheck="false" autocomplete="off" readonly onfocus="this.removeAttribute('readonly');">
            <label class="mdl-textfield__label" for="sample1">Item Sumber Daya</label>
          </div>
          <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label w-10/12">
            <input required class="mdl-textfield__input" name="jumlah-item" id="jumlah-item" type="text" pattern="-?[0-9]*(\.[0-9]+)?" autocorrect="off" spellcheck="false" autocomplete="off" readonly onfocus="this.removeAttribute('readonly');">
            <label class="mdl-textfield__label" for="sample1">Jumlah Item</label>
            <span class="mdl-textfield__error">Input hanya menerima angka!</span>
          </div>
          {% for message in messages %}
            <div class="text-red-400">{{ message }}</div>
          {% endfor %}
          <div class="flex mt-10">
            <button type="submit" class="bg-transparent mx-2 w-36 bg-pink-400 font-bold text-white py-2 px-4 border border-pink-400 rounded mr-2">
              Buat Stok
            </button>
          </div>
        </form>
      </div>
    </section>
  </div>
{% endblock %}

{% block script %}
  <script>
    const handleKodeFaskesSelect = (selectValue) => {
      const dataObject = document.querySelector(`#${selectValue}`);
      const data = dataObject.getAttribute('data-nama');

      const namaFaskesObject = document.querySelector('#nama-faskes');
      namaFaskesObject.parentElement.classList.add('is-dirty');
      namaFaskesObject.value = data;
    };

    const handleItemSumberDayaSelect = (selectValue) => {
      const dataObject = document.querySelector(`#${selectValue}`);
      const data = dataObject.getAttribute('data-nama');

      const itemSumberDayaObject = document.querySelector('#item-sumber-daya');
      itemSumberDayaObject.parentElement.classList.add('is-dirty');
      itemSumberDayaObject.value = data;
    };
  </script>
{% endblock %}

pesanan/templates/pesanan/stok-faskes.html
<!DOCTYPE html>

{% extends 'base.html' %}
{% load static %}

{% block meta %}
{% endblock %}

{% block content %}
  <div class="bg-gray-100">
    <section style="height: 40vh;" class="w-full bg-gradient-to-b from-red-300 to-pink-400 flex flex-col justify-center items-center">
      <h2 class="text-white font-bold text-6xl">Stok Fasilitas Kesehatan</span></h2>
      <div class="flex mt-10">
        <div class="bg-gray-200 text-pink-500 font-bold cursor-default text-xl py-1 px-2 mx-1 rounded">👤 {{ username }}</div>
        <div class="bg-gray-200 text-pink-500 font-bold cursor-default text-xl py-1 px-2 mx-1 rounded">👨‍💼 {{ user_role }}</div>
      </div>
      <a href="{% url 'dashboard:dashboard' %}" class="focus:outline-none">
        <button type="button" class="bg-blue-400 mx-2 w-56 text-white font-bold py-2 px-4 border rounded mr-2 mt-10 focus:outline-none focus:ring">
          Kembali ke Dashboard
        </button>
      </a>
    </section>
    <section style="min-height: 60vh;" class="px-20 py-10">
      <table class="mdl-data-table mdl-js-data-table mdl-shadow--2dp w-full">
        <thead>
          <tr>
            <th class="mdl-data-table__cell--non-numeric">Kode Faskes</th>
            <th class="mdl-data-table__cell--non-numeric">Nama Faskes</th>
            <th class="mdl-data-table__cell--non-numeric">Item Sumber Daya</th>
            <th>Jumlah</th>
            {% if user_role == "Admin Satgas" %}
              <th class="mdl-data-table__cell--non-numeric">Action</th>
            {% endif %}
          </tr>
        </thead>
        <tbody>
          {% for stock in stock_data %}
            <tr>
              <td class="mdl-data-table__cell--non-numeric">{{ stock.kode_faskes }}</td>
              <td class="mdl-data-table__cell--non-numeric">{{ stock.nama_tipe|title }}</td>
              <td class="mdl-data-table__cell--non-numeric">{{ stock.nama }}</td>
              <td>{{ stock.jumlah_item }}</td>
              {% if user_role == "Admin Satgas" %}
                <td class="mdl-data-table__cell--non-numeric">
                  <div class="flex">
                    <a href="{% url 'pesanan:stok-faskes-update' stock.kode_faskes stock.kode_item %}">
                      <div style="margin: 0 4.5px;" class="font-bold cursor-pointer hover:bg-green-500 bg-green-600 p-2 min-w-7 h-7 flex items-center justify-center text-white rounded">Update</div>
                    </a>
                    <a href="{% url 'pesanan:stok-faskes-delete' stock.kode_faskes stock.kode_item %}">
                      <div style="margin: 0 4.5px;" class="font-bold cursor-pointer hover:bg-red-800 bg-red-700 p-2 min-w-7 h-7 flex items-center justify-center text-white rounded">Delete</div>
                    </a>
                  </div>
                </td>
              {% endif %}
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </section>
  </div>
{% endblock %}