cek_lokasi/urls.py
import django.contrib.auth
from django.urls import path, include
from . import views

app_name = 'cek_lokasi'

urlpatterns = [
    # path('', views.cek_lokasi, name='cek_lokasi'),
    path('tambah-faskes/', views.tambah_faskes, name='tambah_faskes'),
    path('tambah-warehouse-satgas/', views.tambah_warehouse_satgas, name='tambah_warehouse_satgas'),
    path('tambah-batch-pengiriman/', views.tambah_batch_pengiriman, name='tambah_batch_pengiriman'),
    path('response-lokasi/', views.perantara, name='perantara'),
    path('response-id/', views.perantara_id, name='perantara_id'),
    path('response-kode/', views.perantara_kode, name='perantara_kode'),
    path('daftar-faskes/', views.insert_to_faskes_table, name='insert_to_faskes_table'),
    path('daftar-warehouse-satgas/', views.insert_to_ws_table, name='insert_to_ws_table'),
    path('faskes/delete/<str:kode_faskes>', views.delete_faskes, name='delete_faskes'),
    path('ws/delete/<str:provinsi>/<str:kabupaten>/<str:kecamatan>/<str:kelurahan>/<str:jalan_no>', views.delete_ws, name='delete_ws'),

]

dashboard/urls.py
import django.contrib.auth
from django.urls import path, include
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.landing, name='landing'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard/admin/', views.dashboard_admin_satgas, name='dashboard-admin-satgas'),
    path('dashboard/faskes/', views.dashboard_petugas_faskes, name='dashboard-petugas-faskes'),
    path('dashboard/supplier/', views.dashboard_supplier, name='dashboard-supplier'),
    path('dashboard/distribusi/', views.dashboard_petugas_distribusi, name='dashboard-petugas-distribusi'),
]

pesanan/urls.py
import django.contrib.auth
from django.urls import path, include
from . import views

app_name = 'pesanan'

urlpatterns = [
    path('pesanan/', views.pesanan, name='pesanan'),
    path('pesanan/create/', views.pesanan_create, name='pesanan-create'),
    path('riwayat/process/<str:no_transaksi>/', views.riwayat_process, name='riwayat-process'),
    path('riwayat/reject/<str:no_transaksi>/', views.riwayat_reject, name='riwayat-reject'),
    path('riwayat/problem/<str:no_transaksi>/', views.riwayat_problem, name='riwayat-problem'),
    path('riwayat/finish/<str:no_transaksi>/', views.riwayat_finish, name='riwayat-finish'),
    path('riwayat/status/<str:no_transaksi>/', views.riwayat_status, name='riwayat-status'),
    path('stok-faskes/', views.stok_faskes, name='stok-faskes'),
    path('stok-faskes/create/', views.stok_faskes_create, name='stok-faskes-create'),
    path('stok-faskes/update/<str:kode_faskes>/<str:kode_item>', views.stok_faskes_update, name='stok-faskes-update'),
    path('stok-faskes/delete/<str:kode_faskes>/<str:kode_item>', views.stok_faskes_delete, name='stok-faskes-delete'),
]

sidia/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('dashboard.urls')),
    path('admin/', admin.site.urls),
    path('user/', include('users.urls')),
    path('cek_lokasi/', include('cek_lokasi.urls')),
    path('kendaraan/', include('kendaraan.urls')),
    path('permohonan/', include('permohonan.urls')),
    path('pesanan/', include('pesanan.urls')),
]

users/urls.py
import django.contrib.auth
from django.urls import path, include
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),
]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from django.db import connection
from django.shortcuts import render, redirect

from .utils import dictfetchall
from users.decorators import is_user_logged_in, is_user_role_correct

def landing(request):
    return render(request, 'dashboard/landing.html')

def dashboard(request):
    user_role = request.session.get('user_role')

    if user_role == "ADMIN_SATGAS":
        return redirect('dashboard:dashboard-admin-satgas')
    elif user_role == "PETUGAS_FASKES":
        return redirect('dashboard:dashboard-petugas-faskes')
    elif user_role == "SUPPLIER":
        return redirect('dashboard:dashboard-supplier')
    elif user_role == "PETUGAS_DISTRIBUSI":
        return redirect('dashboard:dashboard-petugas-distribusi')

    return redirect('users:login')

@is_user_role_correct(["ADMIN_SATGAS"])
def dashboard_admin_satgas(request):
    cursor = connection.cursor()
    cursor.execute('SET SEARCH_PATH TO SIDIA')

    username = request.session.get('username')

    cursor.execute(f'''
        SELECT DISTINCT *
        FROM PENGGUNA
        WHERE username = '{username}'
    ;''')

    profile_data = dictfetchall(cursor)[0]

    context = {}
    context['profile_data'] = profile_data
    context['role_data'] = "Admin Satgas"

    return render(request, 'dashboard/admin-satgas.html', context)

@is_user_role_correct(["PETUGAS_FASKES"])
def dashboard_petugas_faskes(request):
    cursor = connection.cursor()
    cursor.execute('SET SEARCH_PATH TO SIDIA')

    username = request.session.get('username')

    cursor.execute(f'''
        SELECT DISTINCT *
        FROM PENGGUNA
        WHERE username = '{username}'
    ;''')

    profile_data = dictfetchall(cursor)[0]

    context = {}
    context['profile_data'] = profile_data
    context['role_data'] = "Petugas Faskes"

    return render(request, 'dashboard/petugas-faskes.html', context)

@is_user_role_correct(["SUPPLIER"])
def dashboard_supplier(request):
    cursor = connection.cursor()
    cursor.execute('SET SEARCH_PATH TO SIDIA')

    username = request.session.get('username')

    cursor.execute(f'''
        SELECT DISTINCT *
        FROM
            PENGGUNA p,
            SUPPLIER s
        WHERE
            p.username = '{username}' AND
            p.username = s.username
    ;''')

    profile_data = dictfetchall(cursor)[0]

    context = {}
    context['profile_data'] = profile_data
    context['role_data'] = "Supplier"

    return render(request, 'dashboard/supplier.html', context)

@is_user_role_correct(["PETUGAS_DISTRIBUSI"])
def dashboard_petugas_distribusi(request):
    cursor = connection.cursor()
    cursor.execute('SET SEARCH_PATH TO SIDIA')

    username = request.session.get('username')

    cursor.execute(f'''
        SELECT DISTINCT *
        FROM
            PENGGUNA p,
            PETUGAS_DISTRIBUSI pd
        WHERE
            p.username = '{username}' AND
            p.username = pd.username
    ;''')

    profile_data = dictfetchall(cursor)[0]

    context = {}
    context['profile_data'] = profile_data
    context['role_data'] = "Petugas Distribusi"

    return render(request, 'dashboard/petugas-distribusi.html', context)

dashboard/templates/dashboard/admin-satgas.html
<!DOCTYPE html>

{% extends 'base.html' %}
{% load static %}

{% block meta %}
{% endblock %}

{% block content %}
  <div class="bg-gray-100 min-h-screen min-w-screen">
    <section style="height: 50vh;" class="w-full bg-gradient-to-b from-green-400 via-green-500 to-green-600 flex flex-col justify-center items-center">
      <h2 class="text-white font-bold text-6xl">Selamat datang, <span class="text-yellow-400">{{ profile_data.nama }}.</span></h2>
      <div class="flex mt-10">
        <div class="bg-gray-200 text-green-700 font-bold cursor-default text-xl py-1 px-2 mx-1 rounded">👤 {{ profile_data.username }}</div>
        <div class="bg-gray-200 text-green-700 font-bold cursor-default text-xl py-1 px-2 mx-1 rounded">👨‍💼 {{ role_data }}</div>
        <div class="bg-gray-200 text-green-700 font-bold cursor-default text-xl py-1 px-2 mx-1 rounded">🏠 {{ profile_data.alamat_kabkot|lower|title }}, {{ profile_data.alamat_prov|lower|title }}</div>
        <div class="bg-gray-200 text-green-700 font-bold cursor-default text-xl py-1 px-2 mx-1 rounded">📞 {{ profile_data.no_telepon }}</div>
      </div>
      <a href="{% url 'users:logout' %}" class="focus:outline-none">
        <button type="button" class="bg-red-400 mx-2 w-40 text-white font-bold py-2 px-4 border rounded mr-2 mt-10 focus:outline-none focus:ring">
          Keluar
        </button>
      </a>
    </section>
    <section class="w-full bg-gray-100 flex flex-wrap justify-center items-center px-32 pt-5 pb-10">
      <div class="p-5 text-center relative hover:opacity-95 bg-green-500 rounded-md w-48 h-48 text-green-700 text-md flex flex-col justify-center items-center mx-5 mt-5">
        <h5 class="text-white font-bold text-5 text-xl mb-5">Permohonan Sumber Daya</h5>
        <div class="absolute bottom-5 flex justify-around">
          <div style="margin: 0 4.5px;" class="font-bold cursor-pointer hover:bg-yellow-400 bg-yellow-300 w-7 h-7 flex items-center justify-center text-white rounded">R</div>
        </div>
      </div>
      <div class="p-5 text-center relative hover:opacity-95 bg-green-500 rounded-md w-48 h-48 text-green-700 text-md flex flex-col justify-center items-center mx-5 mt-5">
        <h5 class="text-white font-bold text-5 text-xl mb-5">Riwayat Status Permohonan</h5>
        <div class="absolute bottom-5 flex justify-around">
          <div style="margin: 0 4.5px;" class="font-bold cursor-pointer hover:bg-blue-600 bg-blue-500 w-7 h-7 flex items-center justify-center text-white rounded">C</div>
          <div style="margin: 0 4.5px;" class="font-bold cursor-pointer hover:bg-yellow-400 bg-yellow-300 w-7 h-7 flex items-center justify-center text-white rounded">R</div>
        </div>
      </div>
      <div class="p-5 text-center relative hover:opacity-95 bg-green-500 rounded-md w-48 h-48 text-green-700 text-md flex flex-col justify-center items-center mx-5 mt-5">
        <h5 class="text-white font-bold text-5 text-xl mb-5">Item Sumber Daya</h5>
        <div class="absolute bottom-5 flex justify-around">
          <div style="margin: 0 4.5px;" class="font-bold cursor-pointer hover:bg-yellow-400 bg-yellow-300 w-7 h-7 flex items-center justify-center text-white rounded">R</div>
        </div>
      </div>
      <div class="p-5 text-center relative hover:opacity-95 bg-green-500 rounded-md w-48 h-48 text-green-700 text-md flex flex-col justify-center items-center mx-5 mt-5">
        <h5 class="text-white font-bold text-5 text-xl mb-5">Pesanan Sumber Daya</h5>
        <div class="absolute bottom-5 flex justify-around">
          <a href="{% url 'pesanan:pesanan' %}">
            <div style="margin: 0 4.5px;" class="font-bold cursor-pointer hover:bg-blue-600 bg-blue-500 w-7 h-7 flex items-center justify-center text-white rounded">C</div>
          </a>
          <a href="{% url 'pesanan:pesanan' %}">
            <div style="margin: 0 4.5px;" class="font-bold cursor-pointer hover:bg-yellow-400 bg-yellow-300 w-7 h-7 flex items-center justify-center text-white rounded">R</div>
          </a>
        </div>
      </div>
      <div class="p-5 text-center relative hover:opacity-95 bg-green-500 rounded-md w-48 h-48 text-green-700 text-md flex flex-col justify-center items-center mx-5 mt-5">
        <h5 class="text-white font-bold text-5 text-xl mb-5">Riwayat Status Pesanan</h5>
        <div class="absolute bottom-5 flex justify-around">
          <div style="margin: 0 4.5px;" class="font-bold cursor-pointer hover:bg-blue-600 bg-blue-500 w-7 h-7 flex items-center justify-center text-white rounded">C</div>
          <div style="margin: 0 4.5px;" class="font-bold cursor-pointer hover:bg-yellow-400 bg-yellow-300 w-7 h-7 flex items-center justify-center text-white rounded">R</div>
        </div>
      </div>
      <div class="p-5 text-center relative hover:opacity-95 bg-green-500 rounded-md w-48 h-48 text-green-700 text-md flex flex-col justify-center items-center mx-5 mt-5">
        <h5 class="text-white font-bold text-5 text-xl mb-5">Kendaraan</h5>
        <div class="absolute bottom-5 flex justify-around">
          <div style="margin: 0 4.5px;" class="font-bold cursor-pointer hover:bg-blue-600 bg-blue-500 w-7 h-7 flex items-center justify-center text-white rounded">C</div>
          <div style="margin: 0 4.5px;" class="font-bold cursor-pointer hover:bg-yellow-400 bg-yellow-300 w-7 h-7 flex items-center justify-center text-white rounded">R</div>
        </div>
      </div>
      <div class="p-5 text-center relative hover:opacity-95 bg-green-500 rounded-md w-48 h-48 text-green-700 text-md flex flex-col justify-center items-center mx-5 mt-5">
        <h5 class="text-white font-bold text-5 text-xl mb-5">Batch Pengiriman</h5>
        <div class="absolute bottom-5 flex justify-around">
          <div style="margin: 0 4.5px;" class="font-bold cursor-pointer hover:bg-blue-600 bg-blue-500 w-7 h-7 flex items-center justify-center text-white rounded">C</div>
          <div style="margin: 0 4.5px;" class="font-bold cursor-pointer hover:bg-yellow-400 bg-yellow-300 w-7 h-7 flex items-center justify-center text-white rounded">R</div>
        </div>
      </div>
      <div class="p-5 text-center relative hover:opacity-95 bg-green-500 rounded-md w-48 h-48 text-green-700 text-md flex flex-col justify-center items-center mx-5 mt-5">
        <h5 class="text-white font-bold text-5 text-xl mb-5">Riwayat Status Batch</h5>
        <div class="absolute bottom-5 flex justify-around">
          <div style="margin: 0 4.5px;" class="font-bold cursor-pointer hover:bg-blue-600 bg-blue-500 w-7 h-7 flex items-center justify-center text-white rounded">C</div>
          <div style="margin: 0 4.5px;" class="font-bold cursor-pointer hover:bg-yellow-400 bg-yellow-300 w-7 h-7 flex items-center justify-center text-white rounded">R</div>
        </div>
      </div>
      <div class="p-5 text-center relative hover:opacity-95 bg-green-500 rounded-md w-48 h-48 text-green-700 text-md flex flex-col justify-center items-center mx-5 mt-5">
        <h5 class="text-white font-bold text-5 text-xl mb-5">Lokasi</h5>
        <div class="absolute bottom-5 flex justify-around">
          <div style="margin: 0 4.5px;" class="font-bold cursor-pointer hover:bg-blue-600 bg-blue-500 w-7 h-7 flex items-center justify-center text-white rounded">C</div>
          <div style="margin: 0 4.5px;" class="font-bold cursor-pointer hover:bg-yellow-400 bg-yellow-300 w-7 h-7 flex items-center justify-center text-white rounded">R</div>
        </div>
      </div>
      <div class="p-5 text-center relative hover:opacity-95 bg-green-500 rounded-md w-48 h-48 text-green-700 text-md flex flex-col justify-center items-center mx-5 mt-5">
        <h5 class="text-white font-bold text-5 text-xl mb-5">Fasilitas Kesehatan</h5>
        <div class="absolute bottom-5 flex justify-around">
          <a href="{% url 'cek_lokasi:tambah_faskes' %}">
            <div style="margin: 0 4.5px;" class="font-bold cursor-pointer hover:bg-blue-600 bg-blue-500 w-7 h-7 flex items-center justify-center text-white rounded">C</div>
          </a>
          <a href="{% url 'cek_lokasi:insert_to_faskes_table' %}">
            <div style="margin: 0 4.5px;" class="font-bold cursor-pointer hover:bg-yellow-400 bg-yellow-300 w-7 h-7 flex items-center justify-center text-white rounded">R</div>
          </a>
        </div>
      </div>
      <div class="p-5 text-center relative hover:opacity-95 bg-green-500 rounded-md w-48 h-48 text-green-700 text-md flex flex-col justify-center items-center mx-5 mt-5">
        <h5 class="text-white font-bold text-5 text-xl mb-5">Stok Fasilitas Kesehatan</h5>
        <div class="absolute bottom-5 flex justify-around">
          <a class="{% url 'pesanan:stok-faskes-create' %}">
            <div style="margin: 0 4.5px;" class="font-bold cursor-pointer hover:bg-blue-600 bg-blue-500 w-7 h-7 flex items-center justify-center text-white rounded">C</div>
          </a>
          <a class="{% url 'pesanan:stok-faskes' %}">
            <div style="margin: 0 4.5px;" class="font-bold cursor-pointer hover:bg-yellow-400 bg-yellow-300 w-7 h-7 flex items-center justify-center text-white rounded">R</div>
          </a>
        </div>
      </div>
      <div class="p-5 text-center relative hover:opacity-95 bg-green-500 rounded-md w-48 h-48 text-green-700 text-md flex flex-col justify-center items-center mx-5 mt-5">
        <h5 class="text-white font-bold text-5 text-xl mb-5">Warehouse Satgas</h5>
        <div class="absolute bottom-5 flex justify-around">
          <a href="{% url 'cek_lokasi:tambah_warehouse_satgas' %}">
          <div style="margin: 0 4.5px;" class="font-bold cursor-pointer hover:bg-blue-600 bg-blue-500 w-7 h-7 flex items-center justify-center text-white rounded">C</div>
          </a>

          <a href="{% url 'cek_lokasi:insert_to_ws_table' %}">
          <div style="margin: 0 4.5px;" class="font-bold cursor-pointer hover:bg-yellow-400 bg-yellow-300 w-7 h-7 flex items-center justify-center text-white rounded">R</div>
          </a>
        </div>
      </div>
      <div class="p-5 text-center relative hover:opacity-95 bg-green-500 rounded-md w-48 h-48 text-green-700 text-md flex flex-col justify-center items-center mx-5 mt-5">
        <h5 class="text-white font-bold text-5 text-xl mb-5">Stok Warehouse Satgas</h5>
        <div class="absolute bottom-5 flex justify-around">
          <div style="margin: 0 4.5px;" class="font-bold cursor-pointer hover:bg-blue-600 bg-blue-500 w-7 h-7 flex items-center justify-center text-white rounded">C</div>
          <div style="margin: 0 4.5px;" class="font-bold cursor-pointer hover:bg-yellow-400 bg-yellow-300 w-7 h-7 flex items-center justify-center text-white rounded">R</div>
        </div>
      </div>
    </section>
  </div>
{% endblock %}

dashboard/templates/dashboard/petugas-distribusi.html
<!DOCTYPE html>

{% extends 'base.html' %}
{% load static %}

{% block meta %}
{% endblock %}

{% block content %}
  <div class="bg-gray-100 min-h-screen min-w-screen">
    <section style="height: 50vh;" class="w-full bg-gradient-to-b from-green-400 via-green-500 to-green-600 flex flex-col justify-center items-center">
      <h2 class="text-white font-bold text-6xl">Selamat datang, <span class="text-yellow-400">{{ profile_data.nama }}.</span></h2>
      <div class="flex mt-10">
        <div class="bg-gray-200 text-green-700 font-bold cursor-default text-xl py-1 px-2 mx-1 rounded">👤 {{ profile_data.username }}</div>
        <div class="bg-gray-200 text-green-700 font-bold cursor-default text-xl py-1 px-2 mx-1 rounded">👨‍💼 {{ role_data }}</div>
        <div class="bg-gray-200 text-green-700 font-bold cursor-default text-xl py-1 px-2 mx-1 rounded">💳 {{ profile_data.no_sim }}</div>
        <div class="bg-gray-200 text-green-700 font-bold cursor-default text-xl py-1 px-2 mx-1 rounded">🏠 {{ profile_data.alamat_kabkot|lower|title }}, {{ profile_data.alamat_prov|lower|title }}</div>
        <div class="bg-gray-200 text-green-700 font-bold cursor-default text-xl py-1 px-2 mx-1 rounded">📞 {{ profile_data.no_telepon }}</div>
      </div>
      <a href="{% url 'users:logout' %}" class="focus:outline-none">
        <button type="button" class="bg-red-400 mx-2 w-40 text-white font-bold py-2 px-4 border rounded mr-2 mt-10 focus:outline-none focus:ring">
          Keluar
        </button>
      </a>
    </section>
    <section class="w-full bg-gray-100 flex flex-wrap justify-center items-center px-32 pt-5 pb-10">
      <div class="p-5 text-center relative hover:opacity-95 bg-green-500 rounded-md w-48 h-48 text-green-700 text-md flex flex-col justify-center items-center mx-5 mt-5">
        <h5 class="text-white font-bold text-5 text-xl mb-5">Kendaraan</h5>
        <div class="absolute bottom-5 flex justify-around">
          <div style="margin: 0 4.5px;" class="font-bold cursor-pointer hover:bg-yellow-400 bg-yellow-300 w-7 h-7 flex items-center justify-center text-white rounded">R</div>
        </div>
      </div>
      <div class="p-5 text-center relative hover:opacity-95 bg-green-500 rounded-md w-48 h-48 text-green-700 text-md flex flex-col justify-center items-center mx-5 mt-5">
        <h5 class="text-white font-bold text-5 text-xl mb-5">Warehouse Satgas</h5>
        <div class="absolute bottom-5 flex justify-around">
          <div style="margin: 0 4.5px;" class="font-bold cursor-pointer hover:bg-yellow-400 bg-yellow-300 w-7 h-7 flex items-center justify-center text-white rounded">R</div>
        </div>
      </div>
      <div class="p-5 text-center relative hover:opacity-95 bg-green-500 rounded-md w-48 h-48 text-green-700 text-md flex flex-col justify-center items-center mx-5 mt-5">
        <h5 class="text-white font-bold text-5 text-xl mb-5">Stok Warehouse Satgas</h5>
        <div class="absolute bottom-5 flex justify-around">
          <div style="margin: 0 4.5px;" class="font-bold cursor-pointer hover:bg-yellow-400 bg-yellow-300 w-7 h-7 flex items-center justify-center text-white rounded">R</div>
        </div>
      </div>
    </section>
  </div>
{% endblock %}

dashboard/templates/dashboard/supplier.html
<!DOCTYPE html>

{% extends 'base.html' %}
{% load static %}

{% block meta %}
{% endblock %}

{% block content %}
  <div class="bg-gray-100 min-h-screen min-w-screen">
    <section style="height: 50vh;" class="w-full bg-gradient-to-b from-green-400 via-green-500 to-green-600 flex flex-col justify-center items-center">
      <h2 class="text-white font-bold text-6xl">Selamat datang, <span class="text-yellow-400">{{ profile_data.nama }}.</span></h2>
      <div class="flex mt-10">
        <div class="bg-gray-200 text-green-700 font-bold cursor-default text-xl py-1 px-2 mx-1 rounded">👤 {{ profile_data.username }}</div>
        <div class="bg-gray-200 text-green-700 font-bold cursor-default text-xl py-1 px-2 mx-1 rounded">👨‍💼 {{ role_data }}</div>
        <div class="bg-gray-200 text-green-700 font-bold cursor-default text-xl py-1 px-2 mx-1 rounded">🏢 {{ profile_data.nama_organisasi }}</div>
        <div class="bg-gray-200 text-green-700 font-bold cursor-default text-xl py-1 px-2 mx-1 rounded">🏠 {{ profile_data.alamat_kabkot|lower|title }}, {{ profile_data.alamat_prov|lower|title }}</div>
        <div class="bg-gray-200 text-green-700 font-bold cursor-default text-xl py-1 px-2 mx-1 rounded">📞 {{ profile_data.no_telepon }}</div>
      </div>
      <a href="{% url 'users:logout' %}" class="focus:outline-none">
        <button type="button" class="bg-red-400 mx-2 w-40 text-white font-bold py-2 px-4 border rounded mr-2 mt-10 focus:outline-none focus:ring">
          Keluar
        </button>
      </a>
    </section>
    <section class="w-full flex flex-wrap justify-center items-center px-32 pt-5 pb-10">
      <div class="p-5 text-center relative hover:opacity-95 bg-green-500 rounded-md w-48 h-48 text-green-700 text-md flex flex-col justify-center items-center mx-5 mt-5">
        <h5 class="text-white font-bold text-5 text-xl mb-5">Item Sumber Daya</h5>
        <div class="absolute bottom-5 flex justify-around">
          <div style="margin: 0 4.5px;" class="font-bold cursor-pointer hover:bg-blue-600 bg-blue-500 w-7 h-7 flex items-center justify-center text-white rounded">C</div>
          <div style="margin: 0 4.5px;" class="font-bold cursor-pointer hover:bg-yellow-400 bg-yellow-300 w-7 h-7 flex items-center justify-center text-white rounded">R</div>
        </div>
      </div>
      <div class="p-5 text-center relative hover:opacity-95 bg-green-500 rounded-md w-48 h-48 text-green-700 text-md flex flex-col justify-center items-center mx-5 mt-5">
        <h5 class="text-white font-bold text-5 text-xl mb-5">Pesanan Sumber Daya</h5>
        <div class="absolute bottom-5 flex justify-around">
          <div style="margin: 0 4.5px;" class="font-bold cursor-pointer hover:bg-blue-600 bg-blue-500 w-7 h-7 flex items-center justify-center text-white rounded">C</div>
          <div style="margin: 0 4.5px;" class="font-bold cursor-pointer hover:bg-yellow-400 bg-yellow-300 w-7 h-7 flex items-center justify-center text-white rounded">R</div>
          <div style="margin: 0 4.5px;" class="font-bold cursor-pointer hover:bg-gray-400 bg-gray-300 w-7 h-7 flex items-center justify-center text-white rounded">U</div>
        </div>
      </div>
      <div class="p-5 text-center relative hover:opacity-95 bg-green-500 rounded-md w-48 h-48 text-green-700 text-md flex flex-col justify-center items-center mx-5 mt-5">
        <h5 class="text-white font-bold text-5 text-xl mb-5">Fasilitas Kesehatan</h5>
        <div class="absolute bottom-5 flex justify-around">
          <a href="{% url 'cek_lokasi:insert_to_faskes_table' %}">
            <div style="margin: 0 4.5px;" class="font-bold cursor-pointer hover:bg-yellow-400 bg-yellow-300 w-7 h-7 flex items-center justify-center text-white rounded">R</div>
          </a>
        </div>
      </div>
      <div class="p-5 text-center relative hover:opacity-95 bg-green-500 rounded-md w-48 h-48 text-green-700 text-md flex flex-col justify-center items-center mx-5 mt-5">
        <h5 class="text-white font-bold text-5 text-xl mb-5">Warehouse Satgas</h5>
        <div class="absolute bottom-5 flex justify-around">
          <a href="{% url 'cek_lokasi:insert_to_ws_table' %}">
            <div style="margin: 0 4.5px;" class="font-bold cursor-pointer hover:bg-yellow-400 bg-yellow-300 w-7 h-7 flex items-center justify-center text-white rounded">R</div>
            </a>
        </div>
      </div>
      <div class="p-5 text-center relative hover:opacity-95 bg-green-500 rounded-md w-48 h-48 text-green-700 text-md flex flex-col justify-center items-center mx-5 mt-5">
        <h5 class="text-white font-bold text-5 text-xl mb-5">Stok Warehouse Satgas</h5>
        <div class="absolute bottom-5 flex justify-around">
          <div style="margin: 0 4.5px;" class="font-bold cursor-pointer hover:bg-yellow-400 bg-yellow-300 w-7 h-7 flex items-center justify-center text-white rounded">R</div>
        </div>
      </div>
    </section>
  </div>
{% endblock %}